// <auto-generated />
using System;
using HastaneSistemi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HastaneSistemi.Migrations
{
    [DbContext(typeof(HastaneDbContext))]
    [Migration("20250615152017_PoliklinikSeed")]
    partial class PoliklinikSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("HastaneSistemi.Models.AdminBilgileri", b =>
                {
                    b.Property<int>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminID");

                    b.ToTable("Adminler");
                });

            modelBuilder.Entity("HastaneSistemi.Models.DoktorBilgileri", b =>
                {
                    b.Property<int>("DoktorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("AdSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bolum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemaModu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DoktorID");

                    b.ToTable("Doktorlar");
                });

            modelBuilder.Entity("HastaneSistemi.Models.DoktorUygunluk", b =>
                {
                    b.Property<int>("UygunlukID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<TimeSpan>("BaslangicSaat")
                        .HasColumnType("time");

                    b.Property<DateTime>("BaslangicTarih")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("BitisSaat")
                        .HasColumnType("time");

                    b.Property<DateTime>("BitisTarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoktorID")
                        .HasColumnType("int");

                    b.HasKey("UygunlukID");

                    b.ToTable("DoktorUygunluk");
                });

            modelBuilder.Entity("HastaneSistemi.Models.HastaBilgileri", b =>
                {
                    b.Property<string>("TC")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AdSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemaModu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("YaziBuyuk")
                        .HasColumnType("bit");

                    b.HasKey("TC");

                    b.ToTable("Hastalar");
                });

            modelBuilder.Entity("HastaneSistemi.Models.Poliklinik", b =>
                {
                    b.Property<int>("PoliklinikID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ikon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PoliklinikID");

                    b.ToTable("Poliklinikler");

                    b.HasData(
                        new
                        {
                            PoliklinikID = 1,
                            Ad = "Acil Tıp",
                            Ikon = "uil-ambulance"
                        },
                        new
                        {
                            PoliklinikID = 2,
                            Ad = "Aile Hekimliği",
                            Ikon = "uil-user-md"
                        },
                        new
                        {
                            PoliklinikID = 3,
                            Ad = "Anesteziyoloji ve Reanimasyon",
                            Ikon = "uil-clinic-medical"
                        },
                        new
                        {
                            PoliklinikID = 4,
                            Ad = "Beyin ve Sinir Cerrahisi",
                            Ikon = "uil-brain"
                        },
                        new
                        {
                            PoliklinikID = 5,
                            Ad = "Cildiye",
                            Ikon = "uil-swatchbook"
                        },
                        new
                        {
                            PoliklinikID = 6,
                            Ad = "Endokrinoloji ve Metabolizma Hastalıkları",
                            Ikon = "uil-flask"
                        },
                        new
                        {
                            PoliklinikID = 7,
                            Ad = "Enfeksiyon Hastalıkları",
                            Ikon = "uil-virus-slash"
                        },
                        new
                        {
                            PoliklinikID = 8,
                            Ad = "Fiziksel Tıp ve Rehabilitasyon",
                            Ikon = "uil-wheelchair"
                        },
                        new
                        {
                            PoliklinikID = 9,
                            Ad = "Gastroenteroloji",
                            Ikon = "uil-stethoscope"
                        },
                        new
                        {
                            PoliklinikID = 10,
                            Ad = "Genel Cerrahi",
                            Ikon = "uil-hospital"
                        },
                        new
                        {
                            PoliklinikID = 11,
                            Ad = "Genel Dahiliye",
                            Ikon = "uil-medical-drip"
                        },
                        new
                        {
                            PoliklinikID = 12,
                            Ad = "Girişimsel Radyoloji",
                            Ikon = "uil-flask"
                        },
                        new
                        {
                            PoliklinikID = 13,
                            Ad = "Göz Hastalıkları",
                            Ikon = "uil-eye"
                        },
                        new
                        {
                            PoliklinikID = 14,
                            Ad = "Göğüs Cerrahisi",
                            Ikon = "uil-stethoscope"
                        },
                        new
                        {
                            PoliklinikID = 15,
                            Ad = "Göğüs Hastalıkları",
                            Ikon = "uil-stethoscope"
                        },
                        new
                        {
                            PoliklinikID = 16,
                            Ad = "Hematoloji",
                            Ikon = "uil-syringe"
                        },
                        new
                        {
                            PoliklinikID = 17,
                            Ad = "Kadin Hastalıkları",
                            Ikon = "uil-user"
                        },
                        new
                        {
                            PoliklinikID = 18,
                            Ad = "Kalp ve Damar Cerrahisi",
                            Ikon = "uil-heart"
                        },
                        new
                        {
                            PoliklinikID = 19,
                            Ad = "Kardiyoloji",
                            Ikon = "uil-heartbeat"
                        },
                        new
                        {
                            PoliklinikID = 20,
                            Ad = "Kulak Burun Boğaz",
                            Ikon = "uil-headphones"
                        },
                        new
                        {
                            PoliklinikID = 21,
                            Ad = "Nefroloji",
                            Ikon = "uil-kid"
                        },
                        new
                        {
                            PoliklinikID = 22,
                            Ad = "Nöroloji",
                            Ikon = "uil-brain"
                        },
                        new
                        {
                            PoliklinikID = 23,
                            Ad = "Nükleer Tıp",
                            Ikon = "uil-atom"
                        },
                        new
                        {
                            PoliklinikID = 24,
                            Ad = "Ortopedi",
                            Ikon = "uil-wheelchair"
                        },
                        new
                        {
                            PoliklinikID = 25,
                            Ad = "Plastik, Rekonstrüktif ve Estetik Cerrahi",
                            Ikon = "uil-user-check"
                        },
                        new
                        {
                            PoliklinikID = 26,
                            Ad = "Radyasyon Onkolojisi",
                            Ikon = "uil-atom"
                        },
                        new
                        {
                            PoliklinikID = 27,
                            Ad = "Radyoloji",
                            Ikon = "uil-dna"
                        },
                        new
                        {
                            PoliklinikID = 28,
                            Ad = "Romatoloji",
                            Ikon = "uil-wheelchair"
                        },
                        new
                        {
                            PoliklinikID = 29,
                            Ad = "Ruh Sağlığı ve Hastalıkları",
                            Ikon = "uil-user"
                        },
                        new
                        {
                            PoliklinikID = 30,
                            Ad = "Tibbi Biyokimya",
                            Ikon = "uil-flask"
                        },
                        new
                        {
                            PoliklinikID = 31,
                            Ad = "Tibbi Genetik",
                            Ikon = "uil-dna"
                        },
                        new
                        {
                            PoliklinikID = 32,
                            Ad = "Tibbi Mikrobiyoloji",
                            Ikon = "uil-virus-slash"
                        },
                        new
                        {
                            PoliklinikID = 33,
                            Ad = "Tibbi Onkoloji",
                            Ikon = "uil-dna"
                        },
                        new
                        {
                            PoliklinikID = 34,
                            Ad = "Tibbi Patoloji",
                            Ikon = "uil-notes"
                        },
                        new
                        {
                            PoliklinikID = 35,
                            Ad = "Yeni Doğan",
                            Ikon = "uil-baby-carriage"
                        },
                        new
                        {
                            PoliklinikID = 36,
                            Ad = "Çocuk Acil",
                            Ikon = "uil-ambulance"
                        },
                        new
                        {
                            PoliklinikID = 37,
                            Ad = "Çocuk Cerrahisi",
                            Ikon = "uil-syringe"
                        },
                        new
                        {
                            PoliklinikID = 38,
                            Ad = "Çocuk Endokrinolojisi",
                            Ikon = "uil-baby-carriage"
                        },
                        new
                        {
                            PoliklinikID = 39,
                            Ad = "Çocuk Enfeksiyon ve Hastalıkları",
                            Ikon = "uil-virus-slash"
                        },
                        new
                        {
                            PoliklinikID = 40,
                            Ad = "Çocuk Gastroenterolojisi",
                            Ikon = "uil-stethoscope-alt"
                        },
                        new
                        {
                            PoliklinikID = 41,
                            Ad = "Çocuk Hematolojisi ve Onkolojisi",
                            Ikon = "uil-dna"
                        },
                        new
                        {
                            PoliklinikID = 42,
                            Ad = "Çocuk Kardiyolojisi",
                            Ikon = "uil-heart"
                        },
                        new
                        {
                            PoliklinikID = 43,
                            Ad = "Çocuk Nefrolojisi",
                            Ikon = "uil-kid"
                        },
                        new
                        {
                            PoliklinikID = 44,
                            Ad = "Çocuk Nörolojisi",
                            Ikon = "uil-brain"
                        },
                        new
                        {
                            PoliklinikID = 45,
                            Ad = "Çocuk Romatolojisi",
                            Ikon = "uil-wheelchair-alt"
                        },
                        new
                        {
                            PoliklinikID = 46,
                            Ad = "Çocuk Sağlığı ve Hastalıkları",
                            Ikon = "uil-kid"
                        },
                        new
                        {
                            PoliklinikID = 47,
                            Ad = "Çocuk ve Ergen Ruh Sağlığı",
                            Ikon = "uil-user"
                        },
                        new
                        {
                            PoliklinikID = 48,
                            Ad = "Çocuk İmmünolojisi ve Alerji Hastalıkları",
                            Ikon = "uil-syringe"
                        },
                        new
                        {
                            PoliklinikID = 49,
                            Ad = "Üroloji",
                            Ikon = "uil-medkit"
                        },
                        new
                        {
                            PoliklinikID = 50,
                            Ad = "İmmünoloji ve Alerji Hastalıkları",
                            Ikon = "uil-syringe"
                        });
                });

            modelBuilder.Entity("HastaneSistemi.Models.RandevuBilgisi", b =>
                {
                    b.Property<int>("RandevuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Bolum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoktorID")
                        .HasColumnType("int");

                    b.Property<string>("Saat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("TcKimlikNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RandevuID");

                    b.ToTable("Randevular");
                });
#pragma warning restore 612, 618
        }
    }
}
